### ISSUE TITLE
Support Text / Font Icon

### ISSUE THREAD

**Issue by manojdcoder** [bradmartin/nativescript-floatingactionbutton#53] opened 2017-05-20 05:50 UTC
Add support for text / font-icon.

**Comment by bradmartin** [comment] 2017-05-20 12:03
Duplicate of https://github.com/bradmartin/nativescript-floatingactionbutton/issues/20
On Android you'll have a lot of work to make this possible. If you're willing to create a PR with the functionality that would be awesome but I won't have the time to do this myself, especially for Android as it is a lot of work. You can see my comment on the other issue how the Fab on Android inherits from an image class. You would have to add a textview to the Fabs inner view and override some things. So while possible it's time consuming.  Again I'd gladly accept a PR for this but it's a challenge to implement so let me know if you want to attempt and I can help answer any questions. Thanks.

**Comment by manojdcoder** [comment] 2017-05-20 13:57
Thank you @bradmartin, I will check #20 and see if I can work it out

**Comment by bradmartin** [comment] 2017-05-20 14:23
The iOS side might be easier to get working but I know Android will require
a bit of work. Any questions let me know.

**Comment by bigradish** [comment] 2017-10-23 04:39
@bradmartin Maybe you can refer to React Native action button https://github.com/mastermoo/react-native-action-button to implement the Nativescript version.

**Comment by bradmartin** [comment] 2017-10-23 05:01
@bigradish - I don't know RN very well but skimmed that library for any reference to the native Android FloatingActionButton and did not find one. It looks as if that is just a button exposing different options and not the 100% native Android FAB. At any rate, the best way to support text/font icon in a FAB is to use a normal NS button and style it to mimic a FAB. Even the native Android FAB doesn't simply support putting font/text on the widget. You can read some approaches here https://stackoverflow.com/questions/33671196/floatingactionbutton-with-text-instead-of-image

**Closed by bradmartin** 2017-10-23 05:01 UTC

**Comment by xuhcc** [comment] 2019-08-09 08:45
Here's the code to create a FAB with text icon on android:

```html
<Fab (loaded)="onFabLoaded($event)">
```

```typescript
import { Font, FontStyle, FontWeight } from 'tns-core-modules/ui/styling/font';

function textToBitmap(
    text: string,
    fontSize: number,  // Not the same as used in CSS, needs adjustment
    fontColor: string,
    fontFamily: string,  // Could be icon font too
) {
    const nsFont = new Font(fontFamily, 0, FontStyle.NORMAL, FontWeight.NORMAL);
    // Adapted from https://stackoverflow.com/a/39965170/1868395
    const paint = new android.graphics.Paint(android.graphics.Paint.ANTI_ALIAS_FLAG);
    paint.setTextSize(fontSize);
    paint.setColor(android.graphics.Color.parseColor(fontColor));
    paint.setTextAlign(android.graphics.Paint.Align.LEFT);
    paint.setTypeface(nsFont.getAndroidTypeface());
    const baseline = -paint.ascent();
    const width = paint.measureText(text);
    const height = baseline + paint.descent();
    const image = android.graphics.Bitmap.createBitmap(
        width,
        height,
        android.graphics.Bitmap.Config.ARGB_8888,
    );
    const canvas = new android.graphics.Canvas(image);
    canvas.drawText(text, 0, baseline, paint);
    return image;
}

onFabLoaded(args) {
    const fab = args.object;
    const bitmap = textToBitmap('+', 80, '#FFFFFF', 'normal');
    fab.android.setImageBitmap(bitmap);
}
```

**Comment by surdu** [comment] 2020-04-11 15:50
I see that, at least in NS v6.5.0 and above, you can specify an image `src` [like this](https://github.com/NativeScript/nativescript-app-templates/blob/7776c939576bff57267e8aaee3d062e19b6d840b/packages/template-tab-navigation/app/app-root.xml#L9):

```
<Image src="font://&#xf015;" class="fas t-36" />
```

@bradmartin Can't this be leveraged in order to draw font-icons on the floating button ?

**Comment by surdu** [comment] 2020-04-11 18:41
Hmm... actually managed to find how to use font-icons by looking at the source code:
```
<FAB:fab text="&#xf02a;"
	class="fab-button fas" />
```
They points to note are that `fab` components has a `text` property and it considers the font family that you set for the component. If you need to achieve this, you might also want to [read the docs](https://docs.nativescript.org/ui/components/icon-fonts) about icon fonts in {N}.

@bradmartin Would a PR to add this use-case to the docs be welcomed ?

**Comment by bradmartin** [comment] 2020-04-13 17:46
@surdu very much welcome and appreciated, thanks for your information and offer.
